from . import syntax
from .paths import Paths

import datetime
import os
import sys
from pkg_resources import resource_filename

class Generator:
    def __init__(self, out):
        self.w = syntax.Writer(out)

    def controlDict(self, case, timing):
        self.w.build(
                outputs=case.controlDict,
                rule="gen-controlDict",
                inputs=os.path.join("src", "controlDict.template"),
                variables={
                    "endTime": timing.endTime,
                    "writeInterval": timing.writeInterval,
                    "timestep": timing.timestep,
                }
        )
        self.w.newline()

    def copy(self, source, target):
        self.w.build(outputs=str(target), rule="cp", inputs=str(source))

    def copyAll(self, files, source, target):
        for f in files:
            self.copy(os.path.join(str(source), f), os.path.join(str(target), f))

    def copyMesh(self, source, target):
        self.copyAll(Paths.polyMesh, source, target)

    def header(self):
        self.w.comment("Generated by \"{}\"".format(" ".join(sys.argv)))
        self.w.comment("at {}".format(datetime.datetime.utcnow().isoformat()))
        self.w.newline()

    def initialTracer(self, case, tracerFieldDict, staggering):
        self.w.build(
                outputs=case.path('0', staggering.T),
                rule="setInitialTracerField",
                implicit=case.polyMesh + case.systemFiles + 
                         staggering.T_inits(case) +
                        [case.tracerFieldDict],
                variables={"case": case}
        )
        self.w.newline()
        self.copy(tracerFieldDict, case.tracerFieldDict)
        staggering.copyT_Inits(self, case)
        self.w.newline()

    def s3uploadCase(self, case, implicit=[]):
        self.s3upload(case, implicit + case.polyMesh + case.systemFiles)

    def s3upload(self, case, implicit=[]):
        self.w.build(
                outputs=case.s3Uploaded,
                rule="s3-upload",
                implicit=implicit,
                variables={"source": case}
        )
        self.w.newline()

    def scriptRule(self, name, command, description=None, pool=None):
        script, args = command.split(' ', 1)
        self.w.rule(
                name,
                resource_filename('ninjaopenfoam', script) + ' ' + args,
                description=description,
                pool=pool)
        self.w.newline()
